### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by haivala** [synesthesiam/opentts#19]
```
opentts_1  | Traceback (most recent call last):
opentts_1  |   File "/home/opentts/app/app.py", line 54, in <module>
opentts_1  |     _LOOP = asyncio.get_event_loop()
opentts_1  |   File "/usr/lib/python3.9/asyncio/events.py", line 639, in get_event_loop
opentts_1  |     self.set_event_loop(self.new_event_loop())
opentts_1  |   File "/usr/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
opentts_1  |     return self._loop_factory()
opentts_1  |   File "/usr/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
opentts_1  |     super().__init__(selector)
opentts_1  |   File "/usr/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
opentts_1  |     super().__init__()
opentts_1  |   File "/usr/lib/python3.9/asyncio/base_events.py", line 397, in __init__
opentts_1  |     self._clock_resolution = time.get_clock_info('monotonic').resolution
opentts_1  | PermissionError: [Errno 1] Operation not permitted
opentts_1  | Exception ignored in: <function BaseEventLoop.__del__ at 0x76750f58>
opentts_1  | Traceback (most recent call last):
opentts_1  |   File "/usr/lib/python3.9/asyncio/base_events.py", line 681, in __del__
opentts_1  |     _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
opentts_1  |   File "/usr/lib/python3.9/asyncio/base_events.py", line 419, in __repr__
opentts_1  |     f'closed={self.is_closed()} debug={self.get_debug()}>'
opentts_1  |   File "/usr/lib/python3.9/asyncio/base_events.py", line 1909, in get_debug
opentts_1  |     return self._debug
```

Trying to run in raspberry pi 3. My docker-compose

```
  opentts:
    image: synesthesiam/opentts:fi
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
        - "5500:5500"
```

**Comment by haivala** [comment]
had to do https://docs.linuxserver.io/faq
