### ISSUE TITLE
zh not available

### ISSUE THREAD

**Issue by bulolo** [synesthesiam/opentts#28]
docker run -it -p 5500:5500 synesthesiam/opentts:zh

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/10026498/179189744-bec5e30a-3594-433b-a280-66d6e0684e93.png">

**Comment by bulolo** [comment]
```
INFO:opentts:Synthesizing with coqui-tts:zh_baker (2 char(s))...
ERROR:opentts:cannot cache function '__shear_dense': no locator available for file '/home/opentts/app/.venv/lib/python3.9/site-packages/librosa/util/utils.py'
Traceback (most recent call last):
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/quart/app.py", line 1490, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/quart/app.py", line 1536, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/home/opentts/app/app.py", line 718, in app_say
    wav_bytes = await text_to_wav(
  File "/home/opentts/app/app.py", line 368, in text_to_wav
    wavs = [result async for result in wavs_gen]
  File "/home/opentts/app/app.py", line 368, in <listcomp>
    wavs = [result async for result in wavs_gen]
  File "/home/opentts/app/app.py", line 469, in text_to_wavs
    line_wav_bytes = await tts.say(line, voice_id, **say_args)
  File "/home/opentts/app/tts.py", line 1665, in say
    from TTS.utils.synthesizer import Synthesizer
  File "/home/opentts/app/TTS/utils/synthesizer.py", line 11, in <module>
    from TTS.tts.utils.speakers import SpeakerManager
  File "/home/opentts/app/TTS/tts/utils/speakers.py", line 13, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/home/opentts/app/TTS/utils/audio.py", line 3, in <module>
    import librosa
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/librosa/core/audio.py", line 18, in <module>
    from .. import util
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/librosa/util/utils.py", line 1848, in <module>
    def __shear_dense(X, factor=+1, axis=-1):
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/numba/core/decorators.py", line 219, in wrapper
    disp.enable_caching()
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/numba/core/dispatcher.py", line 877, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/numba/core/caching.py", line 610, in __init__
    self._impl = self._impl_class(py_func)
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/numba/core/caching.py", line 347, in __init__
    raise RuntimeError("cannot cache function %r: no locator available "
RuntimeError: cannot cache function '__shear_dense': no locator available for file '/home/opentts/app/.venv/lib/python3.9/site-packages/librosa/util/utils.py'
```

**Comment by jiachengshuai** [comment]
你好，请问怎么解决的？

**Comment by habibliu** [comment]
#!/bin/bash

# OpenTTS Docker container name
CONTAINER_NAME="opentts"
LANGUAGE="zh"
# Function to start OpenTTS
start_opentts() {
    echo "Starting OpenTTS..."
    docker run -p 5500:5500 --name $CONTAINER_NAME -d synesthesiam/opentts:$LANGUAGE
    echo "OpenTTS started on port 5500."
}

# Function to stop OpenTTS
stop_opentts() {
    echo "Stopping OpenTTS..."
    docker stop $CONTAINER_NAME
    docker rm $CONTAINER_NAME
    echo "OpenTTS stopped and removed."
}

# Function to display usage
usage() {
    echo "Usage: $0 {start|stop}"
    exit 1
}

# Check command line arguments
if [ $# -ne 1 ]; then
    usage
fi

case $1 in
    start)
        start_opentts
        ;;
    stop)
        stop_opentts
        ;;
    *)
        usage
        ;;
esac

**Comment by habibliu** [comment]
\#!/bin/bash

\# OpenTTS Docker container name
CONTAINER_NAME="opentts"
LANGUAGE="zh"
\# Function to start OpenTTS
start_opentts() {
    echo "Starting OpenTTS..."
    docker run -p 5500:5500 --name $CONTAINER_NAME -d synesthesiam/opentts:$LANGUAGE
    echo "OpenTTS started on port 5500."
}

\# Function to stop OpenTTS
stop_opentts() {
    echo "Stopping OpenTTS..."
    docker stop $CONTAINER_NAME
    docker rm $CONTAINER_NAME
    echo "OpenTTS stopped and removed."
}

\# Function to display usage
usage() {
    echo "Usage: $0 {start|stop}"
    exit 1
}

\# Check command line arguments
if [ $# -ne 1 ]; then
    usage
fi

case $1 in
    start)
        start_opentts
        ;;
    stop)
        stop_opentts
        ;;
    *)
        usage
        ;;
esac
