### ISSUE TITLE
Could not initialize NNPACK! Reason: Unsupported hardware

### ISSUE THREAD

**Issue by pigping88** [synesthesiam/opentts#35]
‘’‘
INFO:opentts:Synthesizing with coqui-tts:zh_baker (3 char(s))...
 > Using model: tacotron2
 > Model's reduction rate `r` is set to: 2
 > Vocoder Model: fullband_melgan
 > Generator Model: fullband_melgan_generator
 > Discriminator Model: melgan_multiscale_discriminator
INFO:opentts:Synthesizing with coqui-tts:zh_baker (9 char(s))...
 > Text splitted to sentences.
 > Text splitted to sentences.
['门开了.']
['开锁失败请再试一次.']
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
DEBUG:jieba:Loading model from cache /tmp/jieba.cache
Loading model cost 0.891 seconds.
DEBUG:jieba:Loading model cost 0.891 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.
[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.
ERROR:opentts:Sizes of tensors must match except in dimension 1. Got 15 and 39 in dimension 2 (The offending index is 1)
Traceback (most recent call last):
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/quart/app.py", line 1490, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/quart/app.py", line 1536, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/home/opentts/app/app.py", line 718, in app_say
    wav_bytes = await text_to_wav(
  File "/home/opentts/app/app.py", line 368, in text_to_wav
    wavs = [result async for result in wavs_gen]
  File "/home/opentts/app/app.py", line 368, in <listcomp>
    wavs = [result async for result in wavs_gen]
  File "/home/opentts/app/app.py", line 469, in text_to_wavs
    line_wav_bytes = await tts.say(line, voice_id, **say_args)
  File "/home/opentts/app/tts.py", line 1716, in say
    audio = await loop.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/opentts/app/TTS/utils/synthesizer.py", line 303, in tts
    outputs = synthesis(
  File "/home/opentts/app/TTS/tts/utils/synthesis.py", line 271, in synthesis
    outputs = run_model_torch(
  File "/home/opentts/app/TTS/tts/utils/synthesis.py", line 100, in run_model_torch
    outputs = _func(
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/opentts/app/TTS/tts/models/tacotron2.py", line 229, in inference
    decoder_outputs, alignments, stop_tokens = self.decoder.inference(
  File "/home/opentts/app/TTS/tts/layers/tacotron/tacotron2.py", line 397, in inference
    decoder_output, alignment, stop_token = self.decode(memory)
  File "/home/opentts/app/TTS/tts/layers/tacotron/tacotron2.py", line 314, in decode
    self.context = self.attention(
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/opentts/app/TTS/tts/layers/tacotron/attentions.py", line 322, in forward
    attention, _ = self.get_location_attention(query, processed_inputs)
  File "/home/opentts/app/TTS/tts/layers/tacotron/attentions.py", line 252, in get_location_attention
    attention_cat = torch.cat(
RuntimeError: Sizes of tensors must match except in dimension 1. Got 15 and 39 in dimension 2 (The offending index is 1)
ERROR:opentts:Sizes of tensors must match except in dimension 1. Got 15 and 39 in dimension 2 (The offending index is 1)
Traceback (most recent call last):
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/quart/app.py", line 1490, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/quart/app.py", line 1536, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/home/opentts/app/app.py", line 718, in app_say
    wav_bytes = await text_to_wav(
  File "/home/opentts/app/app.py", line 368, in text_to_wav
    wavs = [result async for result in wavs_gen]
  File "/home/opentts/app/app.py", line 368, in <listcomp>
    wavs = [result async for result in wavs_gen]
  File "/home/opentts/app/app.py", line 469, in text_to_wavs
    line_wav_bytes = await tts.say(line, voice_id, **say_args)
  File "/home/opentts/app/tts.py", line 1716, in say
    audio = await loop.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/opentts/app/TTS/utils/synthesizer.py", line 303, in tts
    outputs = synthesis(
  File "/home/opentts/app/TTS/tts/utils/synthesis.py", line 271, in synthesis
    outputs = run_model_torch(
  File "/home/opentts/app/TTS/tts/utils/synthesis.py", line 100, in run_model_torch
    outputs = _func(
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/opentts/app/TTS/tts/models/tacotron2.py", line 229, in inference
    decoder_outputs, alignments, stop_tokens = self.decoder.inference(
  File "/home/opentts/app/TTS/tts/layers/tacotron/tacotron2.py", line 397, in inference
    decoder_output, alignment, stop_token = self.decode(memory)
  File "/home/opentts/app/TTS/tts/layers/tacotron/tacotron2.py", line 314, in decode
    self.context = self.attention(
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/opentts/app/TTS/tts/layers/tacotron/attentions.py", line 322, in forward
    attention, _ = self.get_location_attention(query, processed_inputs)
  File "/home/opentts/app/TTS/tts/layers/tacotron/attentions.py", line 252, in get_location_attention
    attention_cat = torch.cat(
RuntimeError: Sizes of tensors must match except in dimension 1. Got 15 and 39 in dimension 2 (The offending index is 1)
’‘’

**Comment by synesthesiam** [comment]
Are you trying to run this on an `arm64` system?
