### ISSUE TITLE
An execution error occurs when certain strings are included.

### ISSUE THREAD

**Issue by shuhei-fujita** [synesthesiam/opentts#49]
An execution error occurs when certain strings are included.
For example, when a string such as "<" is unborn.

Error Message in Terminal
```
$ docker run -it -p 5500:5500 synesthesiam/opentts:ja

Traceback (most recent call last):
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/quart/app.py", line 1490, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/quart/app.py", line 1536, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/home/opentts/app/app.py", line 718, in app_say
    wav_bytes = await text_to_wav(
  File "/home/opentts/app/app.py", line 368, in text_to_wav
    wavs = [result async for result in wavs_gen]
  File "/home/opentts/app/app.py", line 368, in <listcomp>
    wavs = [result async for result in wavs_gen]
  File "/home/opentts/app/app.py", line 492, in ssml_to_wavs
    for sent_index, sentence in enumerate(
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/gruut/__init__.py", line 79, in sentences
    graph, root = text_processor(text, lang=lang, ssml=ssml, **process_args)
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/gruut/text_processor.py", line 439, in __call__
    return self.process(*args, **kwargs)
  File "/home/opentts/app/.venv/lib/python3.9/site-packages/gruut/text_processor.py", line 490, in process
    root_element = etree.fromstring(f"<speak>{text}</speak>")
  File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 10
```

Error Message in Devtools
```
（インデックス）:190 
        
        
       GET http://0.0.0.0:5500/api/tts?voice=coqui-tts%3Aja_kokoro&lang=ja&vocoder=high&denoiserStrength=0.005&text=%3C%E6%A6%82%E8%A6%81&speakerId=&ssml=true&ssmlNumbers=true&ssmlDates=true&ssmlCurrency=true&cache=false 500 (Internal Server Error)
```

<img width="894" alt="スクリーンショット 2024-01-11 0 08 58" src="https://github.com/synesthesiam/opentts/assets/38001967/68856542-2afa-47a3-b80d-d9b88683c019">

**Comment by shuhei-fujita** [comment]
I had the same problem with `coqui-ai/TTS`, so it is possible that OpenTTS is not the cause, but...🤔

https://github.com/coqui-ai/TTS
